//dữ liệu mẫu là mảng các JS object
//theo thiết kế: https://docs.google.com/spreadsheets/d/1iER7kPLNYPeJ6zvwZ2w_YrTR4o-7ncuyLAIu8O8RI1Y/edit#gid=0
module.exports = [
    {
        maHocPhan: "CTT201",
        tenHocPhan: "An toàn và bảo mật dữ liệu trong hệ thống thông tin",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT202",
        tenHocPhan: "Cơ sở dữ liệu nâng cao",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT203",
        tenHocPhan: "Hệ quản trị cơ sở dữ liệu",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT204",
        tenHocPhan: "Phân tích thiết kế hệ thống thông tin",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT205",
        tenHocPhan: "Phát triển ứng dụng hệ thống thông tin hiện đại",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTH001",
        tenHocPhan: "Những nguyên lý cơ bản của chủ nghĩa Mác - Lênin",
        soTinChi: 5,
        loaiHocPhan: "BB",
        soTietLyThuyet: 75,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,LLTHMLN&TTHCM,"]
    },
    {
        maHocPhan: "CTH002",
        tenHocPhan: "Đường lối cách mạng của ĐCSVN",
        soTinChi: 3,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,LLTHMLN&TTHCM,"]
    },
    {
        maHocPhan: "CTH003",
        tenHocPhan: "Tư tưởng Hồ Chí Minh",
        soTinChi: 2,
        loaiHocPhan: "BB",
        soTietLyThuyet: 30,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,LLTHMLN&TTHCM,"]
    },
    {
        maHocPhan: "PLD001",
        tenHocPhan: "Pháp luật đại cương",
        soTinChi: 3,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,KTXH,"]
    },
    {
        maHocPhan: "KTH001",
        tenHocPhan: "Kinh tế đại cương",
        soTinChi: 2,
        loaiHocPhan: "TC",
        soTietLyThuyet: 30,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,KTXH,"]
    },
    {
        maHocPhan: "XHH001",
        tenHocPhan: "Tâm lý đại cương",
        soTinChi: 2,
        loaiHocPhan: "TC",
        soTietLyThuyet: 30,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,KTXH,"]
    },
    {
        maHocPhan: "XHH002",
        tenHocPhan: "Logic học",
        soTinChi: 2,
        loaiHocPhan: "TC",
        soTietLyThuyet: 30,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,KTXH,"]
    },
    {
        maHocPhan: "PKH101",
        tenHocPhan: "Phương pháp luận sáng tạo",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,KTXH,"]
    },
    {
        maHocPhan: "NNA001",
        tenHocPhan: "Anh văn 1",
        soTinChi: 3,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,NN,"]
    },
    {
        maHocPhan: "NNA002",
        tenHocPhan: "Anh văn 2",
        soTinChi: 3,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,NN,"]
    },
    {
        maHocPhan: "NNA103",
        tenHocPhan: "Anh văn 3",
        soTinChi: 3,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,NN,"]
    },
    {
        maHocPhan: "NNA104",
        tenHocPhan: "Anh văn 4",
        soTinChi: 3,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,NN,"]
    },
    {
        maHocPhan: "TTH007",
        tenHocPhan: "Đại số tuyến tính",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 30,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TTH026",
        tenHocPhan: "Giải tích B1",
        soTinChi: 3,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TTH032",
        tenHocPhan: "Giải tích 2",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 30,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TTH063",
        tenHocPhan: "Toán rời rạc",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 60,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TTH045",
        tenHocPhan: "Xác xuất thống kê",
        soTinChi: 3,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TTH092",
        tenHocPhan: "Thực hành Xác suất thống kê",
        soTinChi: 1,
        loaiHocPhan: "BB",
        soTietLyThuyet: 0,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TTH046",
        tenHocPhan: "Toán học tổ hợp",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TTH047",
        tenHocPhan: "Toán ứng dụng và thống kê",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TTH048",
        tenHocPhan: "Phương pháp tính",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TTH049",
        tenHocPhan: "Lý thuyết số",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TTH050",
        tenHocPhan: "Logic và tính toán vị từ",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "VLH005",
        tenHocPhan: "Vật lý đại cương 1 (Cơ, Nhiệt)",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "VLH006",
        tenHocPhan: "Vật lý đại cương 2 (Điện từ, Quang)",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "DTV001",
        tenHocPhan: "Điện tử căn bản",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 0,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "VLH082",
        tenHocPhan: "Thực hành Vật lý đại cương 1",
        soTinChi: 1,
        loaiHocPhan: "TC",
        soTietLyThuyet: 0,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "VLH083",
        tenHocPhan: "Thực hành Vật lý đại cương 2",
        soTinChi: 1,
        loaiHocPhan: "TC",
        soTietLyThuyet: 0,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "DTV091",
        tenHocPhan: "Thực hành Điện tử căn bản",
        soTinChi: 1,
        loaiHocPhan: "TC",
        soTietLyThuyet: 0,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "CTT003",
        tenHocPhan: "Nhập môn lập trình",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "CTT006",
        tenHocPhan: "Phương pháp lập trình hướng đối tượng",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "CTT008",
        tenHocPhan: "Kỹ thuật lập trình",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "CTT009",
        tenHocPhan: "Nhập môn Công nghệ thông tin 1",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 30,
        soTietThucHanh: 45,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "CTT011",
        tenHocPhan: "Tin học cơ sở",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 15,
        soTietThucHanh: 60,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "CTT010",
        tenHocPhan: "Nhập môn Công nghệ thông tin 2",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 30,
        soTietThucHanh: 45,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "CTT012",
        tenHocPhan: "Thiết kế web",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 15,
        soTietThucHanh: 60,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "CTT013",
        tenHocPhan: "Lập trình ứng dụng web với VB.net",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 15,
        soTietThucHanh: 60,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,GDDC,TTHKHTN,"]
    },
    {
        maHocPhan: "TCH001",
        tenHocPhan: "Thể dục 1",
        soTinChi: 2,
        loaiHocPhan: "BB",
        soTietLyThuyet: 15,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,GDTC&GDQP,"]
    },
    {
        maHocPhan: "TCH002",
        tenHocPhan: "Thể dục 2",
        soTinChi: 2,
        loaiHocPhan: "BB",
        soTietLyThuyet: 15,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,GDTC&GDQP,"]
    },
    {
        maHocPhan: "QPH010",
        tenHocPhan: "Giáo dục quốc phòng",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: null,
        soTietThucHanh: null,
        soTietBaiTap: null,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDDC,GDTC&GDQP,"]
    },
    {
        maHocPhan: "CTT101",
        tenHocPhan: "Cấu trúc dữ liệu và giải thuật",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTCSN,"]
    },
    {
        maHocPhan: "CTT102",
        tenHocPhan: "Cơ sở dữ liệu",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTCSN,"]
    },
    {
        maHocPhan: "CTT103",
        tenHocPhan: "Hệ điều hành",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTCSN,"]
    },
    {
        maHocPhan: "CTT104",
        tenHocPhan: "Kiến trúc máy tính và hợp ngữ",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTCSN,"]
    },
    {
        maHocPhan: "CTT105",
        tenHocPhan: "Mạng máy tính",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTCSN,"]
    },
    {
        maHocPhan: "CTT501",
        tenHocPhan: "Lập trình Windows",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTBBNCN,"]
    },
    {
        maHocPhan: "CTT502",
        tenHocPhan: "Nhập môn công nghệ phần mềm",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTBBNCN,"]
    },
    {
        maHocPhan: "CTT503",
        tenHocPhan: "Kiểm chứng phần mềm",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTBBNCN,"]
    },
    {
        maHocPhan: "CTT504",
        tenHocPhan: "Phân tích và thiết kế phần mềm",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTBBNCN,"]
    },
    {
        maHocPhan: "CTT505",
        tenHocPhan: "Phân tích và quản lý yêu cầu phần mềm",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTBBNCN,"]
    },
    {
        maHocPhan: "CTT506",
        tenHocPhan: "Quản lý dự án phần mềm",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTBBNCN,"]
    },
    {
        maHocPhan: "CTT527",
        tenHocPhan: "Phát triển game",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTBBNCN,"]
    },
    {
        maHocPhan: "CTT528",
        tenHocPhan: "Phát triển ứng dụng web",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTBBNCN,"]
    },
    {
        maHocPhan: "CTT535",
        tenHocPhan: "Phát triển phần mềm cho thiết bị di động",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTBBNCN,"]
    },
    {
        maHocPhan: "CTT123",
        tenHocPhan: "Kỹ năng mềm",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 30,
        soTietThucHanh: 45,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT124",
        tenHocPhan: "Kiến tập nghề nghiệp",
        soTinChi: 2,
        loaiHocPhan: "TC",
        soTietLyThuyet: 15,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT125",
        tenHocPhan: "Khởi nghiệp",
        soTinChi: 3,
        loaiHocPhan: "TC",
        soTietLyThuyet: 30,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT126",
        tenHocPhan: "Quy hoạch tuyến tính",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT127",
        tenHocPhan: "Nhập môn tư duy thuật toán",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT128",
        tenHocPhan: "Thuật toán tổ hợp và ứng dụng",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT129",
        tenHocPhan: "Thực tập thực tế",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT521",
        tenHocPhan: "Các chủ đề nâng cao trong công nghệ phần mềm",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT523",
        tenHocPhan: "Lập trình ứng dụng Java",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT524",
        tenHocPhan: "Công nghệ XML và ứng dụng",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT525",
        tenHocPhan: "Công nghệ Java cho hệ thống phân tán",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT526",
        tenHocPhan: "Kiến trúc phần mềm",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT529",
        tenHocPhan: "Mẫu thiết kế hướng đối tượng và ứng dụng",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT530",
        tenHocPhan: "Mô hình hóa phần mềm",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT531",
        tenHocPhan: "Phát triển phần mềm cho hệ thống nhúng",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT532",
        tenHocPhan: "Phát triển phần mềm nguồn mở",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT533",
        tenHocPhan: "Thanh tra mã nguồn",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT534",
        tenHocPhan: "Thiết kế giao diện",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT536",
        tenHocPhan: "Lập trình hướng đối tượng nâng cao",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT537",
        tenHocPhan: "Đặc tả hình thức",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT541",
        tenHocPhan: "Phát triển ứng dụng web nâng cao",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTNCN,KTTCNCN,"]
    },
    {
        maHocPhan: "CTT991",
        tenHocPhan: "Khóa luận tốt nghiệp",
        soTinChi: 10,
        loaiHocPhan: "TC",
        soTietLyThuyet: 0,
        soTietThucHanh: 300,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTTN,"]
    },
    {
        maHocPhan: "CTT992",
        tenHocPhan: "Thực tập tốt nghiệp",
        soTinChi: 10,
        loaiHocPhan: "TC",
        soTietLyThuyet: 0,
        soTietThucHanh: 300,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTTN,"]
    },
    {
        maHocPhan: "CTT993",
        tenHocPhan: "Đồ án tốt nghiệp",
        soTinChi: 6,
        loaiHocPhan: "TC",
        soTietLyThuyet: 0,
        soTietThucHanh: 180,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTTN,"]
    },
    {
        maHocPhan: "CTT522",
        tenHocPhan: "Các công nghệ mới trong phát triển phần mềm",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTTN,"]
    },
    {
        maHocPhan: "CTT538",
        tenHocPhan: "Đồ án Công nghệ phần mềm",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTTN,"]
    },
    {
        maHocPhan: "CTT539",
        tenHocPhan: "Phát triển game nâng cao",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTTN,"]
    },
    {
        maHocPhan: "CTT540",
        tenHocPhan: "Phát triển ứng dụng cho thiết bị di động nâng cao",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [",KTPM2015,root,KTGDCN,KTTN,"]
    },
    {
        maHocPhan: "",
        tenHocPhan: "",
        soTinChi: 4,
        loaiHocPhan: "TC",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: [""]
    },
]