//dữ liệu mẫu là mảng các JS object
//theo thiết kế: https://docs.google.com/spreadsheets/d/1iER7kPLNYPeJ6zvwZ2w_YrTR4o-7ncuyLAIu8O8RI1Y/edit#gid=0
exports.HocPhan = [
    {
        maHocPhan: "CTT501",
        tenHocPhan: "Lập trình Windows",
        soTinChi: 4,
        loaiHocPhan: "",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT502",
        tenHocPhan: "Nhập môn công nghệ phần mềm",
        soTinChi: 4,
        loaiHocPhan: "",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT503",
        tenHocPhan: "Kiểm chứng phần mềm",
        soTinChi: 4,
        loaiHocPhan: "",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT504",
        tenHocPhan: "Phân tích và thiết kế phần mềm",
        soTinChi: 4,
        loaiHocPhan: "",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT505",
        tenHocPhan: "Phân tích và quản lý yêu cầu phần mềm",
        soTinChi: 4,
        loaiHocPhan: "",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT506",
        tenHocPhan: "Quản lý dự án phần mềm",
        soTinChi: 4,
        loaiHocPhan: "",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT527",
        tenHocPhan: "Phát triển game",
        soTinChi: 4,
        loaiHocPhan: "",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT527",
        tenHocPhan: "Phát triển ứng dụng web",
        soTinChi: 4,
        loaiHocPhan: "",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT527",
        tenHocPhan: "Phát triển phần mềm cho thiết bị di động",
        soTinChi: 4,
        loaiHocPhan: "",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT201",
        tenHocPhan: "An toàn và bảo mật dữ liệu trong hệ thống thông tin",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT202",
        tenHocPhan: "Cơ sở dữ liệu nâng cao",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT203",
        tenHocPhan: "Hệ quản trị cơ sở dữ liệu",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT204",
        tenHocPhan: "Phân tích thiết kế hệ thống thông tin",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    },
    {
        maHocPhan: "CTT205",
        tenHocPhan: "Phát triển ứng dụng hệ thống thông tin hiện đại",
        soTinChi: 4,
        loaiHocPhan: "BB",
        soTietLyThuyet: 45,
        soTietThucHanh: 30,
        soTietBaiTap: 0,
        hocPhanTienQuyet: "",
        hocPhanDeNghiHocTruoc: "",
        chiTietDaoTao: []
    }
]